package rules.diagnostics;
dialect  "mvel"

import com.ftn.sbnz.model.QuestionLayer;
import com.ftn.sbnz.model.DetectionType;
import com.ftn.sbnz.model.Intensity;
import com.ftn.sbnz.model.helper.Diagnostic;
import com.ftn.sbnz.model.helper.DiagnosticState;



query isContainedIn(String s1, String s2)
    DiagnosticState( s1, s2; )
    or
    ((DiagnosticState(x, s2; )) and (isContainedIn (s1, x; )))
end



rule "go4"

when
    $s:String();
    isContainedIn( thing, $s ; )
then
    System.out.println( "thing " + thing + " is in the GAd" );
    insert(thing);
end
