package rules.diagnostics;
dialect  "mvel"

import com.ftn.sbnz.model.QuestionLayer;
import com.ftn.sbnz.model.DetectionType;
import com.ftn.sbnz.model.Intensity;
import com.ftn.sbnz.model.helper.Diagnostic;
import com.ftn.sbnz.model.helper.DiagnosticState;



query getSymptomsOf(String symptom, String mentalState)
    DiagnosticState( symptom, mentalState; )
    or
    ((DiagnosticState(x, mentalState; )) and (getSymptomsOf (symptom, x; )))
end



rule "get all symptoms"

when
    $s:String();
    getSymptomsOf( thing, $s ; )
then
    System.out.println( "thing " + thing + " is in the GAd" );
    insert(thing);
end

//rule "naziv pravila"
//// atributi: sailence, no-loop, agenda-group
//when
//    // Left-side
//then
//    // Right-side
//end