package rules.diagnostics;
dialect  "mvel"

import com.ftn.sbnz.model.QuestionLayer;
import com.ftn.sbnz.model.Question;
import com.ftn.sbnz.model.Intensity;
import com.ftn.sbnz.model.helper.FullAnswer;
import com.ftn.sbnz.model.helper.Diagnostic;
import com.ftn.sbnz.model.helper.DiagnosticState;


rule "transform-answer-diagnostic"
no-loop
agenda-group "transform-diagnostic"
    when
        $a: FullAnswer(positive==false, $s: score)
    then
        System.out.println("Panic negative answer");
        System.out.println($s);
        modify($a){setScore(5-$s);}
        modify($a){setPositive(true);}
end


rule "r1-ansksioznost"
agenda-group "result-diagnostic"
    when
        $d: Diagnostic($uId: userId,
                        detectionType == "USLOVI_ZA_ANKSIOZNOST",
                        questionLayer == QuestionLayer.FIRST,
                        finalResult == false,
                        (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
        not (Diagnostic(userId == $uId, detectionType == "ANKSIOZNOST", questionLayer==QuestionLayer.SECOND))
        not (Diagnostic(userId == $uId, detectionType == "GENERALNI_ANKSIOZNI_POREMECAJ", questionLayer==QuestionLayer.THIRD))
    then
        System.out.println(" Drugi slojjj");
        modify($d){setNextLayer(QuestionLayer.SECOND);}
        modify($d){setNextDetection("ANKSIOZNOST");}
end


rule "r2-anksioznost"
agenda-group "result-diagnostic"
    when
        $d1: Diagnostic($uId: userId,
                            detectionType == "USLOVI_ZA_ANKSIOZNOST",
                            questionLayer == QuestionLayer.FIRST,
                            finalResult == false,
                            (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
        $d2: Diagnostic(userId == $uId,
                        detectionType == "ANKSIOZNOST",
                        questionLayer == QuestionLayer.SECOND,
                        finalResult == false,
                        (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
        not (Diagnostic(userId == $uId, detectionType == "GENERALNI_ANKSIOZNI_POREMECAJ", questionLayer==QuestionLayer.THIRD))

    then
        System.out.println(" Treci slojjj");
        modify($d2){ setNextLayer(QuestionLayer.THIRD);}
        modify($d2){ setNextDetection("GENERALNI_ANKSIOZNI_POREMECAJ");}
end


rule "r3-anksioznost"
agenda-group "result-diagnostic"
    when
       $d1: Diagnostic($uId: userId,
                                detectionType == "USLOVI_ZA_ANKSIOZNOST",
                                questionLayer == QuestionLayer.FIRST,
                                (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
       $d2: Diagnostic(userId == $uId,
                            detectionType == "ANKSIOZNOST",
                            questionLayer == QuestionLayer.SECOND,
                            (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
       $d3: Diagnostic(userId == $uId,
                        detectionType == "GENERALNI_ANKSIOZNI_POREMECAJ",
                        questionLayer == QuestionLayer.THIRD,
                        (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
    then
        System.out.println(" Final result");
        modify($d3){ setFinalResult(true);}
end




rule "r1-panicni-napad"
agenda-group "result-diagnostic"
    when
        $d: Diagnostic($uId: userId,
                        detectionType == "USLOVI_ZA_PANICNI_NAPAD",
                        questionLayer == QuestionLayer.FIRST,
                        finalResult == false,
                        (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
        not (Diagnostic(userId == $uId, detectionType == "PANICNI_NAPAD", questionLayer==QuestionLayer.SECOND))
        not (Diagnostic(userId == $uId, detectionType == "PANICNI_POREMECAJ", questionLayer==QuestionLayer.THIRD))
    then
        System.out.println(" Drugi slojjj panicni napad");
        modify($d){ setNextLayer(QuestionLayer.SECOND);}
        modify($d){ setNextDetection("PANICNI_NAPAD");}
end


rule "r2-panicni-napad"
agenda-group "result-diagnostic"
    when
        $d1: Diagnostic($uId: userId,
                            detectionType == "USLOVI_ZA_PANICNI_NAPAD",
                            questionLayer == QuestionLayer.FIRST,
                            finalResult == false,
                            (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
        $d2: Diagnostic(userId == $uId,
                        detectionType == "PANICNI_NAPAD",
                        questionLayer == QuestionLayer.SECOND,
                        finalResult == false,
                        (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
        not (Diagnostic(userId == $uId, detectionType == "PANICNI_POREMECAJ", questionLayer==QuestionLayer.THIRD))

    then
        System.out.println(" Treci slojjj panicni napad");
        modify($d2){ setNextLayer(QuestionLayer.THIRD);}
        modify($d2){ setNextDetection("PANICNI_POREMECAJ");}
end


rule "r3-panicni-napad"
agenda-group "result-diagnostic"
    when
       $d1: Diagnostic($uId: userId,
                                detectionType == "USLOVI_ZA_PANICNI_NAPAD",
                                questionLayer == QuestionLayer.FIRST,
                                finalResult == false,
                                (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
       $d2: Diagnostic(userId == $uId,
                            detectionType == "PANICNI_NAPAD",
                            questionLayer == QuestionLayer.SECOND,
                            finalResult == false,
                            (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
       $d3: Diagnostic(userId == $uId,
                        detectionType == "PANICNI_POREMECAJ",
                        questionLayer == QuestionLayer.THIRD,
                        finalResult == false,
                        $intensity: intensity,
                        (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
    then
        System.out.println(" Final result panicni napad");
        modify($d3){ setFinalResult(true);}
end



rule "r1-socijalna-anksioznost"
agenda-group "result-diagnostic"
    when
        $d: Diagnostic($uId: userId,
                        detectionType == "USLOVI_ZA_SOCIJALNU_ANKSIOZNOST",
                        questionLayer == QuestionLayer.FIRST,
                        finalResult == false,
                        (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
        not (Diagnostic(userId == $uId, detectionType == "SOCIJALNA_ANKSIOZNOST", questionLayer==QuestionLayer.SECOND))
        not (Diagnostic(userId == $uId, detectionType == "SOCIJALNA_FOBIJA", questionLayer==QuestionLayer.THIRD))
    then
        System.out.println(" Drugi slojjj socijalna anksioznost");
        modify($d){setNextLayer(QuestionLayer.SECOND);}
        modify($d){ setNextDetection("SOCIJALNA_ANKSIOZNOST");}
end


rule "r2-socijalna-anksioznost"
agenda-group "result-diagnostic"
    when
        $d1: Diagnostic($uId: userId,
                            detectionType == "USLOVI_ZA_SOCIJALNU_ANKSIOZNOST",
                            questionLayer == QuestionLayer.FIRST,
                            finalResult == false,
                            (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
        $d2: Diagnostic(userId == $uId,
                        detectionType == "SOCIJALNA_ANKSIOZNOST",
                        questionLayer == QuestionLayer.SECOND,
                        finalResult == false,
                        (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
        not (Diagnostic(userId == $uId, detectionType == "SOCIJALNA_FOBIJA", questionLayer==QuestionLayer.THIRD))

    then
        System.out.println(" Treci slojjj socijalna anksioznost");
        modify($d2){setNextLayer(QuestionLayer.THIRD);}
        modify($d2){ setNextDetection("SOCIJALNA_FOBIJA");}
end


rule "r3-socijalna-anksioznost"
agenda-group "result-diagnostic"
    when
       $d1: Diagnostic($uId: userId,
                                detectionType == "USLOVI_ZA_SOCIJALNU_ANKSIOZNOST",
                                questionLayer == QuestionLayer.FIRST,
                                finalResult == false,
                                (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
       $d2: Diagnostic(userId == $uId,
                            detectionType == "SOCIJALNA_ANKSIOZNOST",
                            questionLayer == QuestionLayer.SECOND,
                            finalResult == false,
                            (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
       $d3: Diagnostic(userId == $uId,
                        detectionType == "SOCIJALNA_FOBIJA",
                        questionLayer == QuestionLayer.THIRD,
                        finalResult == false,
                        (intensity == Intensity.TESKO || intensity == Intensity.DUBOKO))
    then
        System.out.println(" Final result socijalna anksioznost");
        modify($d3){setFinalResult(true);}
end


